version: '2'
services:
  db:
    build: ./db
    container_name: crud-db
    volumes:
      - ./db/database:/data/db
    restart: always
    ports:
      - 27017:27017
  web:
    build: ./web
    container_name: crud-web
    environment:
      - PORT=3004
    ports:
      - 3004:3004
    depends_on:
      - db
